### ISSUE TITLE
base58-native errros

### ISSUE THREAD

**Issue by agarzon** [potcoin/potsight#1]
Followed the steps, and after execute:

```npm install```

I got errors:

```

> base58-native@0.1.2 install /home/xx/Downloads/potsight/node_modules/base58-native
> node-gyp rebuild

make: Entering directory '/home/xx/Downloads/potsight/node_modules/base58-native/build'
  CXX(target) Release/obj.target/base58/src/base58.o
In file included from ../src/base58.cc:7:0:
/home/xx/.node-gyp/6.11.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> VException(const char*)’:
/home/xx/.node-gyp/6.11.4/include/node/v8.h:915:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
In file included from ../src/base58.cc:16:0:
../src/common.h:13:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/common.h:14:12: error: ‘ThrowException’ is not a member of ‘v8’
     return v8::ThrowException(v8::Exception::Error(v8::String::New(msg)));
            ^
../src/common.h:14:52: error: ‘New’ is not a member of ‘v8::String’
     return v8::ThrowException(v8::Exception::Error(v8::String::New(msg)));
                                                    ^
../src/base58.cc: At global scope:
../src/base58.cc:27:22: error: ‘Arguments’ does not name a type
 base58_encode (const Arguments& args)
                      ^
In file included from ../src/base58.cc:7:0:
/home/xx/.node-gyp/6.11.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> base58_encode(const int&)’:
/home/xx/.node-gyp/6.11.4/include/node/v8.h:915:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/base58.cc:29:15: error: within this context
   HandleScope scope;
               ^
../src/base58.cc:31:12: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
   if (args.Length() != 1) {
            ^
../src/base58.cc:34:34: error: invalid types ‘const int[int]’ for array subscript
   if (!Buffer::HasInstance(args[0])) {
                                  ^
../src/base58.cc:37:38: error: invalid types ‘const int[int]’ for array subscript
   v8::Handle<v8::Object> buf = args[0]->ToObject();
                                      ^
../src/base58.cc:113:23: error: ‘New’ is not a member of ‘v8::String’
   Local<String> ret = String::New(str);
                       ^
../src/base58.cc:115:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(ret);
                ^
../src/base58.cc: At global scope:
../src/base58.cc:121:22: error: ‘Arguments’ does not name a type
 base58_decode (const Arguments& args)
                      ^
In file included from ../src/base58.cc:7:0:
/home/xx/.node-gyp/6.11.4/include/node/v8.h: In function ‘v8::Handle<v8::Value> base58_decode(const int&)’:
/home/xx/.node-gyp/6.11.4/include/node/v8.h:915:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/base58.cc:123:15: error: within this context
   HandleScope scope;
               ^
../src/base58.cc:126:10: error: expected primary-expression before ‘*’ token
   Buffer *buf = NULL;
          ^
../src/base58.cc:126:11: error: ‘buf’ was not declared in this scope
   Buffer *buf = NULL;
           ^
../src/base58.cc:131:12: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
   if (args.Length() != 1) {
            ^
../src/base58.cc:134:14: error: invalid types ‘const int[int]’ for array subscript
   if (!args[0]->IsString()) {
              ^
../src/base58.cc:148:31: error: invalid types ‘const int[int]’ for array subscript
   String::Utf8Value str(args[0]->ToString());
                               ^
../src/base58.cc:191:43: error: no matching function for call to ‘New(unsigned int)’
   buf = Buffer::New(nLeadingZeros + tmpLen);
                                           ^
In file included from ../src/base58.cc:11:0:
/home/xx/.node-gyp/6.11.4/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                        ^
/home/xx/.node-gyp/6.11.4/include/node/node_buffer.h:31:40: note:   candidate expects 2 arguments, 1 provided
/home/xx/.node-gyp/6.11.4/include/node/node_buffer.h:34:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/xx/.node-gyp/6.11.4/include/node/node_buffer.h:34:40: note:   candidate expects 3 arguments, 1 provided
/home/xx/.node-gyp/6.11.4/include/node/node_buffer.h:39:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t, node::Buffer::FreeCallback, void*)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/xx/.node-gyp/6.11.4/include/node/node_buffer.h:39:40: note:   candidate expects 5 arguments, 1 provided
/home/xx/.node-gyp/6.11.4/include/node/node_buffer.h:46:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/xx/.node-gyp/6.11.4/include/node/node_buffer.h:46:40: note:   candidate expects 3 arguments, 1 provided
../src/base58.cc:202:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(buf->handle_);
                ^
In file included from ../src/base58.cc:7:0:
/home/xx/.node-gyp/6.11.4/include/node/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/xx/.node-gyp/6.11.4/include/node/v8.h:915:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/base58.cc:216:15: error: within this context
   HandleScope scope;
               ^
../src/base58.cc:217:15: error: ‘New’ is not a member of ‘v8::String’
   target->Set(String::New("base58_encode"), FunctionTemplate::New(base58_encode)->GetFunction());
               ^
../src/base58.cc:217:80: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
   target->Set(String::New("base58_encode"), FunctionTemplate::New(base58_encode)->GetFunction());
                                                                                ^
In file included from ../src/base58.cc:7:0:
/home/xx/.node-gyp/6.11.4/include/node/v8.h:4485:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/xx/.node-gyp/6.11.4/include/node/v8.h:4485:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
/home/xx/.node-gyp/6.11.4/include/node/v8.h:4489:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/xx/.node-gyp/6.11.4/include/node/v8.h:4489:34: note:   candidate expects 6 arguments, 1 provided
../src/base58.cc:218:15: error: ‘New’ is not a member of ‘v8::String’
   target->Set(String::New("base58_decode"), FunctionTemplate::New(base58_decode)->GetFunction());
               ^
../src/base58.cc:218:80: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
   target->Set(String::New("base58_decode"), FunctionTemplate::New(base58_decode)->GetFunction());
                                                                                ^
In file included from ../src/base58.cc:7:0:
/home/xx/.node-gyp/6.11.4/include/node/v8.h:4485:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/xx/.node-gyp/6.11.4/include/node/v8.h:4485:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
/home/xx/.node-gyp/6.11.4/include/node/v8.h:4489:34: note: candidate: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/xx/.node-gyp/6.11.4/include/node/v8.h:4489:34: note:   candidate expects 6 arguments, 1 provided
base58.target.mk:96: recipe for target 'Release/obj.target/base58/src/base58.o' failed
make: *** [Release/obj.target/base58/src/base58.o] Error 1
make: Leaving directory '/home/xx/Downloads/potsight/node_modules/base58-native/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.10.0-35-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/xx/Downloads/potsight/node_modules/base58-native
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! base58-native@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the base58-native@0.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the base58-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs base58-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls base58-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xx/Downloads/potsight/npm-debug.log


```

Ubuntu 16.04 LTS 64-bit
nodejs v6.11.4
 
Does this necessarily requires Node.js v0.10.x ?

**Comment by agarzon** [comment]
Has been years.... nobody cared about this issue, I will close it now.
